CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar NOT NULL UNIQUE,
    login varchar NOT NULL UNIQUE,
    name varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS follow (
    user_id integer NOT NULL REFERENCES users (id),
    friend_id integer NOT NULL REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS genre (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS MPA (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS movie (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    description varchar(200),
    release_date date,
    duration integer,
    rate integer,
    MPA integer REFERENCES MPA (id) REFERENCES MPA (id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id integer NOT NULL REFERENCES movie (id),
    genre_id integer NOT NULL REFERENCES genre (id)
);


CREATE TABLE IF NOT EXISTS likes (
    film_id integer NOT NULL REFERENCES movie (id),
    user_id integer NOT NULL REFERENCES users (id)
);
